import { Domine } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";

const domine = Domine({
  // src: "../../public/Domine-VariableFont_wght.ttf",
  weight: "400",
  variable: "--font-domine",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${domine.className} lowercase antialiased `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster richColors closeButton/>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
